/**
 * Flowtype definitions for index
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.16.2
 */

// declare module "express-promise-router" {
//   import type { Router, RouterOptions } from "express";

//   declare function PromiseRouter(options?: RouterOptions): Router;

//   declare export default typeof PromiseRouter;
// }
